name: Build and Test Qt Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt and X11 dependencies
      run: |
        sudo apt update
        sudo apt install -y qt5-qmake qtbase5-dev xvfb x11-utils \
          libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 \
          libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0

    - name: Build Project
      run: |
        qmake
        make

    - name: Run Application (Headless)
      run: |
        xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" ./Project &

    - name: Run Tests (Headless)
      run: |
        xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" ./Project
